builds:
  - env:
      - CGO_ENABLED=0
    id: "qq"
    binary: qq
    goos:
      - linux
      - darwin
      - windows
    ldflags: -s -w -X main.version={{.Version}} -X "main.installFrom=Binary"
archives:
  - format_overrides:
      - goos: windows
        format: zip
changelog:
  use: github-native
  sort: desc
  filters:
    exclude:
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
brews:
  - tap:
      owner: bayashi
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://github.com/bayashi/qq
    description: "References of Quick Questions"
    test: |
      system "#{bin}/qq", '--version'
